# Generated by Django 4.0.6 on 2022-07-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Version',
        ),
    ]
