# Generated by Django 4.0.6 on 2022-07-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='Kill Me Now', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.TextField(default='Kill Me', null=True),
        ),
    ]
