# Generated by Django 4.0.6 on 2022-07-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_userprofile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dp',
            field=models.ImageField(default='profile_images/default.jpg', upload_to='profile_images/%Y-%m-%d'),
        ),
    ]
