# Generated by Django 4.0.6 on 2022-07-19 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0013_alter_userprofile_bio_alter_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mail_followers',
            field=models.ManyToManyField(blank=True, related_name='mail_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
